"use client";

import { useEffect, useState } from "react";
import type { ReportCategory } from "@prisma/client";
import { CheckCircle2, Loader2, Mail, TriangleAlert } from "lucide-react";
import { ButtonLink } from "@/components/shared/button";
import { clearQuestionnaireSession } from "@/lib/questionnaire-session";

type StatusPayload = {
  paymentStatus: string;
  selectedPackage?: string | null;
  generationStatus: string;
  emailStatus: string;
  pdfUrl?: string | null;
  previewTitle?: string | null;
  generationError?: string | null;
  emailMessage?: string | null;
  category?: string;
  hasConstructionLeadRequest?: boolean;
};

function ConstructionLeadOffer({
  requestId,
  hasConstructionLeadRequest
}: {
  requestId: string;
  hasConstructionLeadRequest?: boolean;
}) {
  return (
    <div className="mt-8 rounded-[32px] border border-slate-200 bg-slate-50 p-8 shadow-soft">
      <p className="text-xs uppercase tracking-[0.28em] text-slate-400">Construction leads</p>
      <h3 className="mt-3 font-display text-4xl text-navy-950">Optional manual leads packages</h3>
      <p className="mt-4 max-w-2xl text-sm leading-7 text-slate-600">
        After buying your construction PDF, users can also choose a separate paid leads plan. The leads are genuine opportunities sent by email manually by your team, not generated by AI.
      </p>
      <div className="mt-6 grid gap-4 sm:grid-cols-3 text-sm text-slate-600">
        <div className="rounded-[22px] border border-slate-200 bg-white px-4 py-4">8-10 leads per month at £89.99 / month</div>
        <div className="rounded-[22px] border border-slate-200 bg-white px-4 py-4">2-3 leads per day at £250 / month</div>
        <div className="rounded-[22px] border border-slate-200 bg-white px-4 py-4">No commission is taken from the jobs won</div>
      </div>
      <div className="mt-6 flex flex-col gap-4 sm:flex-row sm:items-center">
        <ButtonLink href={`/construction-leads/${requestId}`}>View leads plans</ButtonLink>
        {hasConstructionLeadRequest ? <p className="text-sm text-slate-500">A construction leads plan has already been requested or activated for this report.</p> : null}
      </div>
    </div>
  );
}

export function ReportStatusCard({ requestId, sessionId }: { requestId: string; sessionId?: string | null }) {
  const [status, setStatus] = useState<StatusPayload | null>(null);

  useEffect(() => {
    let timer: NodeJS.Timeout | undefined;

    async function loadStatus() {
      const params = new URLSearchParams();
      if (sessionId) {
        params.set("session_id", sessionId);
      }

      const query = params.toString();
      const response = await fetch(`/api/reports/${requestId}/status${query ? `?${query}` : ""}`, { cache: "no-store" });
      if (!response.ok) {
        return;
      }

      const data = (await response.json()) as StatusPayload;
      setStatus(data);

      if (data.generationStatus !== "COMPLETED" && data.generationStatus !== "FAILED") {
        timer = setTimeout(loadStatus, 3000);
      }
    }

    loadStatus();
    return () => {
      if (timer) clearTimeout(timer);
    };
  }, [requestId, sessionId]);

  useEffect(() => {
    if (!status?.category) {
      return;
    }

    if (status.paymentStatus === "PAID") {
      clearQuestionnaireSession(status.category as ReportCategory, requestId);
    }
  }, [requestId, status?.category, status?.paymentStatus]);

  const showConstructionOffer = status?.category === "CONSTRUCTION_GROWTH";

  if (status?.paymentStatus && status.paymentStatus !== "PAID") {
    return (
      <div className="rounded-[32px] border border-amber-200 bg-amber-50 p-8 shadow-soft">
        <div className="flex items-center gap-3 text-amber-900">
          <Loader2 className="h-5 w-5 animate-spin" />
          <p className="font-semibold">We are still waiting for payment confirmation.</p>
        </div>
        <p className="mt-4 text-sm leading-7 text-amber-900">
          If you just completed checkout, give this page a moment to update. If payment was cancelled, you can safely return to pricing and try again.
        </p>
        <div className="mt-6">
          <ButtonLink href={`/pricing/${requestId}`} variant="secondary">
            Return to pricing
          </ButtonLink>
        </div>
      </div>
    );
  }

  if (!status || status.generationStatus === "QUEUED" || status.generationStatus === "GENERATING") {
    return (
      <>
        <div className="rounded-[32px] border border-slate-200 bg-white p-8 shadow-soft">
          <div className="flex items-center gap-3 text-navy-950">
            <Loader2 className="h-5 w-5 animate-spin" />
            <p className="font-semibold">We are generating your report now.</p>
          </div>
          <p className="mt-4 text-sm leading-7 text-slate-600">
            Keep this page open. As soon as your PDF is ready, we will update this state and send the file to your inbox.
          </p>
        </div>
        {showConstructionOffer ? (
          <ConstructionLeadOffer requestId={requestId} hasConstructionLeadRequest={status?.hasConstructionLeadRequest} />
        ) : null}
      </>
    );
  }

  if (status.generationStatus === "FAILED") {
    return (
      <>
        <div className="rounded-[32px] border border-red-200 bg-red-50 p-8 shadow-soft">
          <div className="flex items-center gap-3 text-red-800">
            <TriangleAlert className="h-5 w-5" />
            <p className="font-semibold">We hit a generation issue.</p>
          </div>
          <p className="mt-4 text-sm leading-7 text-red-700">
            The payment is safe. Please contact support and include your request ID: {requestId}
          </p>
          {status.generationError ? <p className="mt-3 text-sm text-red-700">{status.generationError}</p> : null}
          <div className="mt-6 flex flex-col gap-3 sm:flex-row">
          <ButtonLink href={`/pricing/${requestId}`} variant="secondary">
            Review pricing
          </ButtonLink>
          <ButtonLink href="/contact" variant="secondary">
            Contact support
          </ButtonLink>
        </div>
      </div>
        {showConstructionOffer ? (
          <ConstructionLeadOffer requestId={requestId} hasConstructionLeadRequest={status?.hasConstructionLeadRequest} />
        ) : null}
      </>
    );
  }

  return (
    <>
      <div className="rounded-[32px] border border-slate-200 bg-white p-8 shadow-soft">
        <div className="flex items-center gap-3 text-emerald-700">
          <CheckCircle2 className="h-6 w-6" />
          <p className="font-semibold">Your report is ready.</p>
        </div>
        <h2 className="mt-5 font-display text-4xl text-navy-950">{status.previewTitle}</h2>
        <p className="mt-4 text-sm leading-7 text-slate-600">
          Download the PDF below. {status.emailStatus === "SENT" ? "A copy has also been sent to your email." : "You can download the PDF here even if email sending is not set up yet."}
        </p>
        <div className="mt-8 flex flex-col gap-4 sm:flex-row sm:flex-wrap">
          {status.pdfUrl ? <ButtonLink href={status.pdfUrl}>Download PDF</ButtonLink> : null}
          <div className="inline-flex items-center gap-2 rounded-full border border-slate-200 px-4 py-3 text-sm text-slate-600">
            <Mail className="h-4 w-4" />
            Email status: {status.emailStatus.replaceAll("_", " ").toLowerCase()}
          </div>
        </div>
        {status.emailMessage ? <p className="mt-4 text-sm text-slate-500">{status.emailMessage}</p> : null}
      </div>
      {showConstructionOffer ? (
        <ConstructionLeadOffer requestId={requestId} hasConstructionLeadRequest={status.hasConstructionLeadRequest} />
      ) : null}
    </>
  );
}
